export enum ConfigurationVariables {
    JWT_SECRET = "JWT_SECRET",
    JWT_EXPIRATION = "JWT_EXPIRATION",
    RESET_PASSWORD_EXPIRATION = "RESET_PASSWORD_EXPIRATION",
    CREATE_PASSWORD_EXPIRATION = "CREATE_PASSWORD_EXPIRATION",
    SALT_ROUNDS = "SALT_ROUNDS",
}
